apiVersion: v1
kind: Service
metadata:
  labels:
    name: sentinel
    role: service
  name: redis-sentinel
spec:
  ports:
    - port: 26381
      targetPort: 26381
  selector:
    redis-sentinel: "true"
